In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

In [27]:
#crate a dataset 
x,y = make_classification(n_samples=100,n_features=10,n_classes=2,random_state=42)

In [28]:
x

array([[-1.14052601,  1.35970566,  0.86199147,  0.84609208,  0.60600995,
        -1.55662917,  1.75479418,  1.69645637, -1.28042935, -2.08192941],
       [-0.07873421, -1.32933233,  0.6273745 , -1.19300559, -0.77300978,
         0.0976761 ,  0.49799829,  0.95927083,  0.02451017,  1.45114361],
       [ 0.80742726,  0.73019848, -1.28568005,  0.88948365, -1.8048821 ,
        -0.76325916,  0.04808495, -0.90431663, -1.62754244,  0.2597225 ],
       [ 0.58846525, -0.3751207 , -0.57500215, -0.14951801, -0.56372455,
         0.41293145,  0.24368721, -0.50694318, -0.8222204 ,  0.24496657],
       [ 1.63631177, -1.64060704, -1.36045573, -0.94116325, -1.43014138,
         1.6324113 ,  0.13074058, -1.43586215, -0.44004449,  1.44127329],
       [-0.47936995, -1.08324727,  1.02255619, -1.09939128, -2.30192116,
        -0.2750517 ,  1.36687427, -0.24903604, -1.51519106,  1.64496771],
       [ 2.48904785, -2.52343407, -2.05832072, -1.45612516, -0.05952536,
        -0.92693047, -1.02438764, -1.24778318

In [29]:
y

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [31]:
#model traing
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [32]:
logistic.fit(x_train,y_train)

LogisticRegression()

In [33]:
y_pred = logistic.predict(x_test)
print(y_pred)

[0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1]


In [34]:
logistic.predict_proba(x_test)

array([[7.49632742e-01, 2.50367258e-01],
       [5.71492961e-02, 9.42850704e-01],
       [8.47383467e-03, 9.91526165e-01],
       [3.84386602e-02, 9.61561340e-01],
       [2.79853023e-02, 9.72014698e-01],
       [9.64640318e-01, 3.53596817e-02],
       [9.65369374e-01, 3.46306260e-02],
       [2.13024820e-01, 7.86975180e-01],
       [2.27546362e-01, 7.72453638e-01],
       [1.81401566e-01, 8.18598434e-01],
       [9.87298049e-01, 1.27019510e-02],
       [1.84390109e-03, 9.98156099e-01],
       [1.11638160e-03, 9.98883618e-01],
       [9.98846835e-01, 1.15316489e-03],
       [3.19528899e-03, 9.96804711e-01],
       [9.75335190e-01, 2.46648100e-02],
       [2.79003416e-02, 9.72099658e-01],
       [9.72840626e-01, 2.71593739e-02],
       [9.57717728e-01, 4.22822718e-02],
       [9.96764165e-01, 3.23583540e-03],
       [3.26255970e-02, 9.67374403e-01],
       [9.91543744e-01, 8.45625612e-03],
       [6.48321099e-01, 3.51678901e-01],
       [9.99581102e-01, 4.18898067e-04],
       [4.128605

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = logistic.predict(x_test)
acc = accuracy_score(y_test, y_pred)
cnn = confusion_matrix(y_test, y_pred)
rep = classification_report(y_test, y_pred)

print("Accuracy:", acc)
print("Confusion Matrix:\n", cnn)
print("Classification Report:\n", rep)

print(rep)

Accuracy: 0.9333333333333333
Confusion Matrix:
 [[12  2]
 [ 0 16]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



## Hyperparameter Tuning and Cross Validation 

In [72]:
model = LogisticRegression(max_iter=1000)
penalty = ['l1','l2','elasticnet']
c = [100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs','liblinear','sag','saga']

In [73]:
params = dict(penalty = penalty,C= c,solver = solver)
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [74]:
# Grid searchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(5)
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [75]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [76]:
grid.fit(x_train,y_train)

/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [77]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'liblinear'}

In [78]:
y_pred = grid.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = logistic.predict(x_test)
acc = accuracy_score(y_test, y_pred)
cnn = confusion_matrix(y_test, y_pred)
rep = classification_report(y_test, y_pred)

print("Accuracy:", acc)
print("Confusion Matrix:\n", cnn)
print("Classification Report:\n", rep)

print(rep)

Accuracy: 0.9333333333333333
Confusion Matrix:
 [[12  2]
 [ 0 16]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



## Randomized  searchCV

In [99]:
import warnings
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings("ignore", category=ConvergenceWarning)
from sklearn.model_selection import RandomizedSearchCV

In [100]:
model  = LogisticRegression()

param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet'],
    'C': [0.1, 1, 10],
    'solver': ['saga'],  # saga supports all penalties
    'l1_ratio': [0.5]     # needed only for elasticnet
}

randomcv = RandomizedSearchCV(estimator=model,param_distributions=param_grid,cv=5,scoring='accuracy')

In [ ]:
randomcv.fit(x_train,y_train)

/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1196: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1196: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1196: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_mode

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.1, 1, 10], 'l1_ratio': [0.5],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['saga']},
                   scoring='accuracy')

In [86]:
randomcv.best_score_

np.float64(0.9857142857142858)

In [87]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'l1_ratio': 0.5, 'C': 10}

In [89]:
y_pred = randomcv.predict(x_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = logistic.predict(x_test)
acc = accuracy_score(y_test, y_pred)
cnn = confusion_matrix(y_test, y_pred)
rep = classification_report(y_test, y_pred)

print("Accuracy:", acc)
print("Confusion Matrix:\n", cnn)
print("Classification Report:\n", rep)
print(rep)

Accuracy: 0.9333333333333333
Confusion Matrix:
 [[12  2]
 [ 0 16]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.89      1.00      0.94        16

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



## Logistic Regresssion For Multiclass Classification Problem

In [92]:
x,y = make_classification(n_classes=3,n_features=10,n_informative=3,n_samples=1000,random_state=42)

In [93]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [94]:
x

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]], shape=(1000, 10))

In [95]:
from sklearn.model_selection import train_test_split

x_train ,x_test , y_train, y_test = train_test_split(x, y, test_size=0.03,random_state=42)

In [96]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression(multi_class='ovr')

logistic.fit(x_train,y_train)

y_pred = logistic.predict(x_test)

/Users/sankar/Documents/Udemy AI /venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [97]:
y_pred

array([2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       2, 0, 1, 0, 2, 0, 0, 2])

In [98]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = logistic.predict(x_test)
acc = accuracy_score(y_test, y_pred)
cnn = confusion_matrix(y_test, y_pred)
rep = classification_report(y_test, y_pred)

print("Accuracy:", acc)
print("Confusion Matrix:\n", cnn)
print("Classification Report:\n", rep)

print(rep)

Accuracy: 0.6
Confusion Matrix:
 [[7 1 1]
 [5 2 4]
 [0 1 9]]
Classification Report:
               precision    recall  f1-score   support

           0       0.58      0.78      0.67         9
           1       0.50      0.18      0.27        11
           2       0.64      0.90      0.75        10

    accuracy                           0.60        30
   macro avg       0.58      0.62      0.56        30
weighted avg       0.57      0.60      0.55        30

              precision    recall  f1-score   support

           0       0.58      0.78      0.67         9
           1       0.50      0.18      0.27        11
           2       0.64      0.90      0.75        10

    accuracy                           0.60        30
   macro avg       0.58      0.62      0.56        30
weighted avg       0.57      0.60      0.55        30

