In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
x,y = load_iris(return_X_y=True)

In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.50,random_state=42)

In [7]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train,y_train)

GaussianNB()

In [9]:
y_pred = gnb.predict(x_test)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

acc = accuracy_score(y_pred,y_test)

report = classification_report(y_pred,y_test)

con = confusion_matrix(y_pred,y_test)

print(con)
print(acc)
print(report)

[[29  0  0]
 [ 0 23  1]
 [ 0  0 22]]
0.9866666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      0.96      0.98        24
           2       0.96      1.00      0.98        22

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75



In [10]:
import seaborn as sns 
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [11]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [12]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [13]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [14]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [15]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [16]:
x = df[['total_bill', 'tip', 'sex', 'smoker', 'day','size']]
y = df['time']

In [29]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=10)

In [30]:
from sklearn.preprocessing import LabelEncoder

lab1 = LabelEncoder()
lab2 = LabelEncoder()

x_train['sex'] = lab1.fit_transform(x_train['sex'])
x_train['smoker'] = lab2.fit_transform(x_train['smoker'])

In [31]:
x_train.head()

total_bill   tip  sex  smoker   day  size
39        31.27  5.00    1       0   Sat     3
87        18.28  4.00    1       0  Thur     2
169       10.63  2.00    0       1   Sat     2
232       11.61  3.39    1       0   Sat     2
144       16.43  2.30    0       0  Thur     2

In [32]:
x_train.tail()

total_bill   tip  sex  smoker   day  size
64        17.59  2.64    1       0   Sat     3
15        21.58  3.92    1       0   Sun     2
228       13.28  2.72    1       0   Sat     2
125       29.80  4.20    0       0  Thur     6
9         14.78  3.23    1       0   Sun     2

In [33]:
x_test['sex'] =lab1.transform(x_test['sex'])
x_test['smoker'] =lab2.transform(x_test['smoker'])

In [34]:
x_test.head()

total_bill   tip  sex  smoker  day  size
162       16.21  2.00    0       0  Sun     3
60        20.29  3.21    1       1  Sat     2
61        13.81  2.00    1       1  Sat     2
63        18.29  3.76    1       1  Sat     4
69        15.01  2.09    1       1  Sat     2

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[4])],
                                     remainder='passthrough')

In [37]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x_train = ct.fit_transform(x_train)

In [38]:
x_test = ct.transform(x_test)

In [39]:
x_test

array([[ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  0.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.

In [40]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train,y_train)

GaussianNB()

In [42]:
gnb.predict([[0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.]])

array(['Dinner'], dtype='<U6')

In [43]:
y_pred1 = gnb.predict(x_test)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

acc = accuracy_score(y_pred1,y_test)

report = classification_report(y_pred1,y_test)

con = confusion_matrix(y_pred1,y_test)

print(con)
print(acc)
print(report)

[[51  0]
 [ 3 20]]
0.9594594594594594
              precision    recall  f1-score   support

      Dinner       0.94      1.00      0.97        51
       Lunch       1.00      0.87      0.93        23

    accuracy                           0.96        74
   macro avg       0.97      0.93      0.95        74
weighted avg       0.96      0.96      0.96        74

